#!/bin/bash 

B_LEFT=$(acpi | grep -oP '\d\d(?=%)') 

if [ $B_LEFT -lt 15 ]
then
	echo $(/usr/bin/date) >> /home/roar/.config/dunst/logs
	export DISPLAY=:0 
	$(/usr/bin/notify-send "Low-Battery" -u CRITICAL) 
fi

