#!/bin/bash 

B_LEFT=$(acpi | grep -oP '\d+(?=%)') 
DISCHARGING=$(acpi | grep -oP 'Discharging')

if [ $B_LEFT -lt 20 ]
then
	#echo $(/usr/bin/date) >> /home/roar/.config/dunst/logs
	if [ -z "$DISCHARGING" ]; then
		export DISPLAY=:0 
		$(/usr/bin/notify-send "Low-Battery" -u CRITICAL) 
	fi

fi 

